### ISSUE TITLE
Add wifimanager timeout

### ISSUE THREAD

**Issue by valerio-vaccaro** [SandboxElectronics/LoRaGoDOCK-Gateway#3]
If you have a temporary problem with the wifi during the board boot or reboot, it will automatically turn on configuration mode enabling AP and provide a captive portal.
Unfortunately the board will not try more to connect on the wifi, with pull request "Add wifimanager timeout #2" I simply added a timeout to the default wifimanager portal in order to retry (every 180 seconds) to connect to the wifi. 
If the temporary problem is resolved the board automatically reconnect with a maximum delay of 180 seconds.

**Comment by covra** [comment]
Can you explain how did you that? (Post code)

thanks

**Comment by valerio-vaccaro** [comment]
After the line `wifiManager.autoConnect(...`  just set the timeout for the portal with the command `wifiManager.setConfigPortalTimeout(180);`. You can also watch the pull request https://github.com/SandboxElectronics/LoRaGoDOCK-Gateway/pull/2/commits/3911e7bd8cedb3de5e46ed44b5f56a28f6dbbb51

**Comment by covra** [comment]
Good work :+1:

**Comment by valerio-vaccaro** [comment]
Merged at https://github.com/SandboxElectronics/LoRaGoDOCK-Gateway/commit/fd177d16a5ae1292155891473f0027bd4c194dcc
